set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]
set_property PACKAGE_PIN M19 [get_ports enable]
set_property PACKAGE_PIN L19 [get_ports reset_rtl]

set_property IOSTANDARD LVCMOS33 [get_ports active]
set_property PACKAGE_PIN M14 [get_ports active]

set_property IOSTANDARD LVCMOS33 [get_ports {choice_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choice_1[1]}]
set_property PACKAGE_PIN U8 [get_ports {choice_1[0]}]
set_property PACKAGE_PIN V7 [get_ports {choice_1[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {choice_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {choice_2[1]}]
set_property PACKAGE_PIN U7 [get_ports {choice_2[0]}]
set_property PACKAGE_PIN C20 [get_ports {choice_2[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports draadloos_signal_connected]
set_property IOSTANDARD LVCMOS33 [get_ports draadloos_signal_up]
set_property IOSTANDARD LVCMOS33 [get_ports draadloos_signal_down]
set_property PACKAGE_PIN Y18 [get_ports draadloos_signal_connected]
set_property PACKAGE_PIN W19 [get_ports draadloos_signal_up]
set_property PACKAGE_PIN W18 [get_ports draadloos_signal_down]

set_property IOSTANDARD LVCMOS33 [get_ports inductieve_sensor_in]
set_property PACKAGE_PIN W6 [get_ports inductieve_sensor_in]

set_property IOSTANDARD LVCMOS33 [get_ports ultrasoon_sensor]
set_property IOSTANDARD LVCMOS33 [get_ports ultrasoon_trigger]
set_property PACKAGE_PIN Y6 [get_ports ultrasoon_sensor]
set_property PACKAGE_PIN V6 [get_ports ultrasoon_trigger]

set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_1[8]}]
set_property PACKAGE_PIN W9 [get_ports {controller_output_1[0]}]
set_property PACKAGE_PIN Y8 [get_ports {controller_output_1[1]}]
set_property PACKAGE_PIN W8 [get_ports {controller_output_1[2]}]
set_property PACKAGE_PIN U18 [get_ports {controller_output_1[3]}]
set_property PACKAGE_PIN Y19 [get_ports {controller_output_1[4]}]
set_property PACKAGE_PIN Y16 [get_ports {controller_output_1[5]}]
set_property PACKAGE_PIN W10 [get_ports {controller_output_1[6]}]
set_property PACKAGE_PIN V10 [get_ports {controller_output_1[7]}]
set_property PACKAGE_PIN V8 [get_ports {controller_output_1[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {controller_output_2[8]}]
set_property PACKAGE_PIN Y9 [get_ports {controller_output_2[0]}]
set_property PACKAGE_PIN A20 [get_ports {controller_output_2[1]}]
set_property PACKAGE_PIN B19 [get_ports {controller_output_2[2]}]
set_property PACKAGE_PIN B20 [get_ports {controller_output_2[3]}]
set_property PACKAGE_PIN Y17 [get_ports {controller_output_2[4]}]
set_property PACKAGE_PIN U19 [get_ports {controller_output_2[5]}]
set_property PACKAGE_PIN F19 [get_ports {controller_output_2[6]}]
set_property PACKAGE_PIN F20 [get_ports {controller_output_2[7]}]
set_property PACKAGE_PIN Y7 [get_ports {controller_output_2[8]}]