set_property IOSTANDARD LVCMOS33 [get_ports enable_0]
set_property IOSTANDARD LVCMOS33 [get_ports enable_1]
set_property IOSTANDARD LVCMOS33 [get_ports freq_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]

set_property PACKAGE_PIN M19 [get_ports enable_0]
set_property PACKAGE_PIN M20 [get_ports enable_1]
set_property PACKAGE_PIN Y9 [get_ports freq_in_0]
set_property PACKAGE_PIN L19 [get_ports reset_rtl]

set_property IOSTANDARD LVCMOS33 [get_ports signal_connected_0]
set_property IOSTANDARD LVCMOS33 [get_ports signal_up_0]
set_property IOSTANDARD LVCMOS33 [get_ports signal_down_0]

set_property PACKAGE_PIN Y18 [get_ports signal_connected_0]
set_property PACKAGE_PIN W19 [get_ports signal_up_0]
set_property PACKAGE_PIN W18 [get_ports signal_down_0]

set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_1[8]}]

set_property PACKAGE_PIN W9 [get_ports {value_out_1[0]}]
set_property PACKAGE_PIN Y8 [get_ports {value_out_1[1]}]
set_property PACKAGE_PIN W8 [get_ports {value_out_1[2]}]
set_property PACKAGE_PIN U18 [get_ports {value_out_1[3]}]
set_property PACKAGE_PIN Y19 [get_ports {value_out_1[4]}]
set_property PACKAGE_PIN Y16 [get_ports {value_out_1[5]}]
set_property PACKAGE_PIN W10 [get_ports {value_out_1[6]}]
set_property PACKAGE_PIN V10 [get_ports {value_out_1[7]}]
set_property PACKAGE_PIN V8 [get_ports {value_out_1[8]}]