set_property IOSTANDARD LVCMOS33 [get_ports enable_0]
set_property IOSTANDARD LVCMOS33 [get_ports freq_in_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_rtl]

set_property PACKAGE_PIN M19 [get_ports enable_0]
set_property PACKAGE_PIN Y9 [get_ports freq_in_0]
set_property PACKAGE_PIN L19 [get_ports reset_rtl]

set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {value_out_0[8]}]

set_property PACKAGE_PIN W9 [get_ports {value_out_0[0]}]
set_property PACKAGE_PIN Y8 [get_ports {value_out_0[1]}]
set_property PACKAGE_PIN W8 [get_ports {value_out_0[2]}]
set_property PACKAGE_PIN U18 [get_ports {value_out_0[3]}]
set_property PACKAGE_PIN Y19 [get_ports {value_out_0[4]}]
set_property PACKAGE_PIN Y16 [get_ports {value_out_0[5]}]
set_property PACKAGE_PIN W10 [get_ports {value_out_0[6]}]
set_property PACKAGE_PIN V10 [get_ports {value_out_0[7]}]
set_property PACKAGE_PIN V8 [get_ports {value_out_0[8]}]

set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_0[3]}]

set_property PACKAGE_PIN M14 [get_ports {leds_0[0]}]
set_property PACKAGE_PIN N16 [get_ports {leds_0[1]}]
set_property PACKAGE_PIN P14 [get_ports {leds_0[2]}]
set_property PACKAGE_PIN R14 [get_ports {leds_0[3]}]